FROM almalinux:9.2

RUN dnf -y update
# Adding epel for screen and xclock
RUN dnf -y install epel-release
RUN dnf -y update

# Various deps
RUN dnf -y install vim man screen xclock xorg-x11-xauth xdg-utils clang clang-tools-extra llvm

# Deps for coding e.g. building root
RUN dnf -y install patch libuuid libuuid-devel

# Deps for ROOT (see https://root.cern/install/dependencies/)
RUN dnf -y install git make cmake gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel compat-openssl11

# Dir for course specific material
ENV MNXB11_MNXB11DIR=/opt
# Dir for all downloads
ENV MNXB11_DOWNLOADS=${MNXB11_MNXB11DIR}/download
RUN mkdir ${MNXB11_DOWNLOADS}
# Dir for all sources, a subfolder for each source tree
ENV MNXB11_SOURCEDIR=${MNXB11_MNXB11DIR}/source
RUN mkdir $MNXB11_SOURCEDIR
# Dir for all builds, a subfolder for each build environment
ENV MNXB11_BUILDDIR=${MNXB11_MNXB11DIR}/build
RUN mkdir $MNXB11_BUILDDIR
# Dir for all binaries, a subfolder for each software
ENV MNXB11_APPS=${MNXB11_MNXB11DIR}/apps
RUN mkdir ${MNXB11_APPS}
# Dir for all scripts
ENV MNXB11_SCRIPTS=${MNXB11_MNXB11DIR}/scripts
RUN mkdir ${MNXB11_SCRIPTS}
# Do we need a custom LIBS folder?

# Place all precompiled software in a folder called "apps" in the folder where you
# run `docker build`. The following line will copy all of them in ${APPS}.
# Note: one app per folder, to keep consistency.
ADD apps $MNXB11_APPS

# Add all scripts in a scripts folder where this is ran
ADD scripts/* ${MNXB11_SCRIPTS}/

CMD ["/bin/bash"]
