FROM almalinux:9.2

RUN dnf -y update
# Adding epel for screen and xclock
RUN dnf -y install epel-release
RUN dnf -y update

# Various deps
RUN dnf -y install vim man screen xclock xorg-x11-xauth xdg-utils clang clang-tools-extra llvm

# Deps for coding e.g. building root
RUN dnf -y install patch libuuid libuuid-devel

# Deps for ROOT (see https://root.cern/install/dependencies/)
RUN dnf -y install git make cmake gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel compat-openssl11

# Dir for course specific material
ENV MNXB11DIR=/opt
# Dir for all downloads
ENV DOWNLOADS=${MNXB11DIR}/download
RUN mkdir ${DOWNLOADS}
# Dir for all sources, a subfolder for each source tree
ENV SOURCEDIR=${MNXB11DIR}/source
RUN mkdir $SOURCEDIR
# Dir for all builds, a subfolder for each build environment
ENV BUILDDIR=${MNXB11DIR}/build
RUN mkdir $BUILDDIR
# Dir for all binaries, a subfolder for each software
ENV APPS=${MNXB11DIR}/apps
RUN mkdir ${APPS}
# Dir for all scripts
ENV SCRIPTS=${MNXB11DIR}/scripts
RUN mkdir ${SCRIPTS}
# Do we need a custom LIBS folder?

# Place all precompiled software in a folder called "apps" in the folder where you
# run `docker build`. The following line will copy all of them in ${APPS}.
# Note: one app per folder, to keep consistency.
ADD apps $APPS

# Add all scripts in a scripts folder where this is ran
ADD scripts/* ${SCRIPTS}/

CMD ["/bin/bash"]
