FROM almalinux:9.2

RUN dnf -y update
RUN dnf -y install vim man
# Deps for coding e.g. building root
RUN dnf -y install patch libuuid libuuid-devel

# Deps for ROOT (see https://root.cern/install/dependencies/)
RUN dnf -y install git make cmake gcc-c++ gcc binutils libX11-devel libXpm-devel libXft-devel libXext-devel python openssl-devel compat-openssl11

# Dir for course specific material
ENV MNXB11DIR=/opt
# Dir for all downloads
ENV DOWNLOADS=${MNXB11DIR}/download
RUN mkdir ${DOWNLOADS}
# Dir for all sources, a subfolder for each source tree
ENV SOURCEDIR=${MNXB11DIR}/source
RUN mkdir $SOURCEDIR
# Dir for all builds, a subfolder for each build environment
ENV BUILDDIR=${MNXB11DIR}/build
RUN mkdir $BUILDDIR
# Dir for all binaries, a subfolder for each software
ENV APPS=${MNXB11DIR}/apps
RUN mkdir ${APPS}
# Dir for all scripts
ENV SCRIPTS=${MNXB11DIR}/scripts
RUN mkdir ${SCRIPTS}

# ROOT build
# Download sources
ADD https://root.cern/download/root_v6.28.04.source.tar.gz ${DOWNLOADS}/root_v6.28.04.source.tar.gz
# Unpack
RUN tar zxf ${DOWNLOADS}/root_v6.28.04.source.tar.gz -C ${SOURCES}

# Add all scripts in a scripts folder where this is ran
ADD scripts /opt/scripts

CMD ["/bin/bash"]
